version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest-node-browsers
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log selenium.log
          background: true      
         
      - run:
          name: install dependencies
          command: |
            export PATH=$PATH:/src/chromedriver
            export PATH=$PATH:/src/geckodriver
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest tests/testfactorialcalculator.py -p no:warnings --html=reports/report.html --durations=0 --alluredir ~/reports/raw_test_result_jsons
            allure generate -c ~/reports/raw_test_result_jsons -o ~/reports
      - store_artifacts:
          path: reports
          destination: reports
          when: always
